#/*
#*
#* HW Mutex Makefile
#* Description: HW Mutex makefile
#*
#*/

EXTRA_CFLAGS += -Iinclude/asm-arm/arch-avalanche/generic
EXTRA_CFLAGS += -Iinclude/linux
EXTRA_CFLAGS += -Iinclude/asm-arm/arch-avalanche/puma6

obj-y := hw_mutex.o hw_mutex_lld.o
